name: 'wait_for_ping_action'
description: 'Check ping, wait for pingable'
author: 'aps-m'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'network'
  color: 'orange'

# Define your inputs here.
inputs:
  tries:
    description: 'Number of ping tries'
    required: true
    default: 1

  host:
    description: 'Host to ping'
    required: true
    default: 'localhost'

runs:
  using: node20
  main: dist/index.js
